from mongoengine import *

class Wechat_articles(Document):
    _id = StringField(required=True)
    id = StringField()
    content = StringField()
    title = StringField()
    post_date = StringField()
    user = StringField()
    keyword = ListField()
    txt_info = StringField()
    txt_info_en = StringField()
    subject = StringField()
    province = StringField()
    status = StringField()
    abstract_cn = StringField()
    abstract_en = StringField()
    page = IntField()
    is_useful = BooleanField()
    repeat_num = IntField()
    show_in_report = BooleanField()
    original_user = StringField()
    share_notice =StringField()
    abstract = StringField()
    show_index = IntField()
    to_check_translate = BooleanField()
    to_translate = BooleanField()
    content_en_machine = StringField()
    title_en_machine = StringField()
    title_en = StringField()
    to_filter = BooleanField()
    to_check = BooleanField()

class Weibo_content(Document):
    _id = StringField(required=True)
    id = StringField()
    subject = StringField()
    user_id = StringField()
    user_name = StringField()
    content = StringField()
    content_en = StringField()
    repost = IntField()
    comment = IntField()
    like = IntField()
    time = StringField()
    date = StringField()
    source = StringField()
    user_sex = StringField()
    user_location = StringField()
    user_birthday = StringField()
    user_province = StringField()
    user_province_en = StringField()
    user_intro = StringField()
    user_ident = StringField()
    keyword = ListField()
    user_list = ListField()
    is_ori = IntField()
    ori_weibo_id = StringField()
    ori_user_name = StringField()
    ori_user_id = StringField()
    ori_user_card = StringField()
    ori_content =StringField()
    ori_repost = IntField()
    ori_comment = IntField()
    ori_like = IntField()
    ori_time = StringField()
    ori_date = StringField()
    ori_source = StringField()
    user_follow_count = IntField()
    user_followers_count = IntField()
    user_verified = BooleanField()
    user_verified_type = IntField()
    ori_user_birthday = StringField()
    ori_user_follow_count = IntField()
    ori_user_followers_count = IntField()
    ori_user_ident = StringField()
    ori_user_intro = StringField()
    ori_user_location = StringField()
    ori_user_province = StringField()
    ori_user_sex = StringField()
    ori_user_verified = BooleanField()
    ori_user_verified_type = IntField()
    is_most_reposted = BooleanField()
    is_auth = BooleanField()
    show_in_report = BooleanField()
    is_verified = BooleanField()
    user_verified_reason = StringField()
    user_description = StringField()
    show_index = IntField()
    repeat_num = IntField()
    ori_url = StringField()
    content_href = DictField()
    ori_content_href = DictField()
    url = StringField()
    ori_id = StringField()
    source_code = StringField()
    is_hot = BooleanField()
    is_related = BooleanField()
    is_useful = BooleanField()
    to_filter = BooleanField()
    to_check = BooleanField()

class News_articles(Document):
    _id = StringField(required=True)
    id = StringField()
    crawl_time = StringField()
    source = StringField()
    source_en = StringField()
    content = StringField()
    url = StringField()
    keyword = StringField()
    time = StringField()
    chinese_summary = StringField()
    title = StringField()
    title_en = StringField()
    abstract_cn = StringField()
    abstract_en = StringField()
    is_useful = BooleanField()
    to_filter = BooleanField()
    to_check = BooleanField()
    content_type = StringField()
    news_subject = StringField()
    attitude = StringField()
    province = StringField()

class Daily_report(Document):
    _id = StringField(required=True)
    fat_news_report = StringField()
    salt_news_report = StringField()
    fat_weibo_report = StringField()
    salt_weibo_report = StringField()
    fat_wechat_report = StringField()
    salt_wechat_report = StringField()

class Weibo_notes(Document):
    _id = StringField(required=True)
    salt_male = IntField()
    salt_female = IntField()
    fat_male = IntField()
    fat_female = IntField()

class User_account(Document):
    _id = StringField(required=True)
    name = StringField()
    password = StringField()

class Daily_count(Document):
    _id = StringField(required=True)
    news_salt_count = IntField()
    news_fat_count = IntField()
    important_salt = IntField()
    important_fat = IntField()
    wechat_salt_count = IntField()
    wechat_fat_count = IntField()
    weibo_salt_count = IntField()
    weibo_fat_count = IntField()
    hot_salt = IntField()
    hot_fat = IntField()